apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-customer-management-config
  namespace: ns-customers
  labels:
    app: ms-customer-management
data:
  API_PORT: "8080"
  API_ENV_NAME: production
  API_VERSION: v1
  DB_NAME: customers
  DB_URL: todo
  DB_URL_SECRET_NAME: db-customers-url-secret