apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-customer-management-hpa
  namespace: ns-customers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-customer-management
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50