apiVersion: v1
kind: Service
metadata:
  name: ms-customer-management
  namespace: ns-customers
  labels:
    app: ms-customer-management
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: ms-customer-management