// Code generated by mockery v2.42.3. DO NOT EDIT.

package delete_request

import (
	context "context"

	entity "github.com/jfelipearaujo-org/ms-customer-management/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *MockRepository) Create(ctx context.Context, request entity.DeletionRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.DeletionRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCustomerId provides a mock function with given fields: ctx, customerId
func (_m *MockRepository) GetByCustomerId(ctx context.Context, customerId string) (entity.DeletionRequest, error) {
	ret := _m.Called(ctx, customerId)

	if len(ret) == 0 {
		panic("no return value specified for GetByCustomerId")
	}

	var r0 entity.DeletionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.DeletionRequest, error)); ok {
		return rf(ctx, customerId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.DeletionRequest); ok {
		r0 = rf(ctx, customerId)
	} else {
		r0 = ret.Get(0).(entity.DeletionRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
